### ISSUE TITLE
eLAIX and LibreOffice 5 - extensions.libreoffice.org throws a warning

### ISSUE THREAD

**Issue by HaakonME** [eLAIX/eLAIX#45]
Hi, Harry! eLAIX is much appreciated and I the warning at http://extensions.libreoffice.org/extension-center/elaix about it might put some users off using it. Just wanted to give you a heads up. Keep up the good work!

**Comment by harry-boldt** [comment]
Hi Haakon,

I'm aware of that warning, but thank you anyway for your hint. Time to publish a new eLAIX version ;-). I'm working on that. 

Are you a subscriber of the eLAIX newsletter (http://elaix.org/newsletter-en.html)? If so, you will be automatically informed about the upcoming of the new version.

Btw, do you understand german? Or do you know someone how can? There's a new manual I wrote, explaining in detail, what you have to do, in order to prepare your documents for high sophisticated output. Download: http://elaix.org/files/elaix/blog/eLAIX-Content-Styles.odt

Regards
Harry


--
BOLDT MEDIA
Dr. phil., Dipl.-Ing. Harry Boldt
Medienpädagoge, Ingenieur für Biomedizinische Technik
Richard-Wagner-Str. 4
52078 Aachen
Tel +49 241 46361877
Fax +49 241 46371531
Mobil +49 1520 1901633
Web: www.boldt-media.de
Mail: harry.boldt@boldt-media.de

**Comment by HaakonME** [comment]
Hi Harry,

Great!

No, thanks for the tip, I usually do not subscribe to newsletters.

Some, but I do know quite a few people in Germany, and will forward your request to them.

Best wishes,
Haakon

**Comment by HaakonME** [comment]
My German friend said it read okay, some small problems detected by spell checker.
